name: Trigger auto deployment for onboarding-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'HRM/Services/OnBoarding/**'
    - '.github/workflows/onboarding-container-AutoDeployTrigger-52d28a9a-7b33-4047-8855-cac8a79ef2a3.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ONBOARDINGCONTAINER_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/HRM/Services/OnBoarding 
          registryUrl: may2023elaine.azurecr.io
          registryUsername: ${{ secrets.ONBOARDINGCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ONBOARDINGCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: onboarding-container
          resourceGroup: May2023Batch
          imageToBuild: may2023elaine.azurecr.io/onboarding-microservice:${{ github.sha }}
          dockerfilePath: Dockerfile

     

