name: Trigger auto deployment for recruiting-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'HRM/Services/Recruiting/**'
    - '.github/workflows/recruiting-container-AutoDeployTrigger-60b9232c-b789-4294-b6fc-2be9e4148590.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.RECRUITINGCONTAINER_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/HRM/Services/Recruiting 
          registryUrl: may2023elaine.azurecr.io
          registryUsername: ${{ secrets.RECRUITINGCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RECRUITINGCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: recruiting-container
          resourceGroup: May2023Batch
          imageToBuild: may2023elaine.azurecr.io/recruiting-container:${{ github.sha }}
          dockerfilePath: Dockerfile

     

